version: '3.1'
services:
  db:
    container_name: forum-db
    restart: always
    image: forum-db
    build:
      context: ./backend/db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
        - ./.env
    networks:
      - default
    ports:
      - 5432:5432

  graphql:
    container_name: forum-graphql
    restart: always
    image: forum-graphql
    build:
      context: ./backend/graphql
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - default
    ports:
      - 5433:5433
    command: [
      "postgraphile",
      "--connection", "${DATABASE_URL}",
      "--port", "5433",
      "--schema", "forum_example",
      "--append-plugins", "postgraphile-plugin-connection-filter",
      "--jwt-token-identifier", "forum_example.jwt_token",
      "--default-role", "forum_example_anonymous",
      "--jwt-secret", "${JWT_SECRET}"
    ]

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8080:8080"
    networks:
      - default
    volumes:
      - ./frontend/build:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - db
      - graphql

volumes:
    db: